name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - run: env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o vrmerge-${{ matrix.goos }}-${{ matrix.goarch }} ./...
      - uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: vrmerge-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: binaries
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            vrmerge-linux-amd64
            vrmerge-windows-amd64.exe
            vrmerge-darwin-amd64