name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - run: env GOOS=windows GOARCH=amd64 go build -o vrmerge-windows.exe ./...
      - run: env GOOS=darwin GOARCH=amd64 go build -o vrmerge-darwin ./...
      - run: env GOOS=linux GOARCH=amd64 go build -o vrmerge-linux ./...
      - uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: vrmerge-*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: binaries
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            vrmerge-*